--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NgLamVN/LMAO
build-by-default: true
branches:
- main
projects:
  LMAO:
    path: ""
    icon: "icon.png"
    libs:
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
...
